### ISSUE TITLE
Getting Black screen

### ISSUE THREAD

**Issue by keyurparalkar** [cornedor/react-native-video-player#10]
Hi Team,

I am having a problem with video playback. There is no video playing on the app just getting black screen.?
screenshot:

![screenshot](https://cloud.githubusercontent.com/assets/14138515/21963816/ba482bd4-db66-11e6-958b-0759d1cbe1e7.png)

**Comment by mbenjamin618** [comment]
Hi,

Do you have the thumbnail prop enabled? It's a required field.

**Comment by cornedor** [comment]
I'll change it so that the thumbnail is not required to show the controls.

**Comment by cornedor** [comment]
I've changed this in v0.5.0

**Comment by keyurparalkar** [comment]
That solved the problem thanks !
