### ISSUE TITLE
TypeError: One of the sources for assign has an enumerable key on the prototype chain

### ISSUE THREAD

**Issue by xcv58** [cornedor/react-native-video-player#100]
RN 0.56.0

```
Unhandled JS Exception: TypeError: TypeError: TypeError: One of the sources for assign has an enumerable key on the prototype chain. Are you trying to assign a prototype property? We don't allow it, as this is an edge case that we do not support. This error is a performance optimization and not spec compliant.
```

![image](https://user-images.githubusercontent.com/503123/44566528-f3741d80-a722-11e8-8f43-a57943443dfc.png)

**Comment by xcv58** [comment]
It caused by this line: https://github.com/cornedor/react-native-video-player/blob/cbe92667fc9c5ae0ac2e31071de990aa8d755eb0/index.js#L357

If I comment this line it works well.

**Comment by TheRav3n** [comment]
Closing as solved.
