### ISSUE TITLE
seekable seekbar

### ISSUE THREAD

**Issue by thynan** [cornedor/react-native-video-player#11]
Hi!

You have a "Make seek bar seekable" task in the readme. Any plans when this will be done? Or did you already implement this, and i'm missing something?

Thanks for the great work so far!

**Comment by cornedor** [comment]
I still have to implement this, I can't promise when this will be done, but I hope to have time for that soon.

**Comment by PeTRoLi** [comment]
I also wait bro. Thank you for support

**Comment by PeTRoLi** [comment]
How I can get callback when video finished?

**Comment by cornedor** [comment]
@PeTRoLi I've just published v0.5.1, that version works with the onEnd callback, so you could just do:
`<VideoPlayer onEnd={() => console.log('Done!')} />`

**Comment by PeTRoLi** [comment]
@cornedor Thank you so much.

**Comment by thynan** [comment]
Ok, that's great news! Just in case you haven't noticed: there is a fork of this repo, where "seekability" has beenimplemented:

https://github.com/ming436534/react-native-video-player. 

However he' using a dependency to react-native-material-kit, and some other dependiencies which unfortunately break my project. But maybe it can be useful for your implementation?

**Comment by cornedor** [comment]
@thynan thanks for pointing that out. Using react-native-material-kit as a dependency is indeed quite overkill, but I might be able to reuse some of his code..

**Comment by thynan** [comment]
Hi! Any news on this? I'm just asking, because I need this feature early next week, and if you are sure you won't have time to implement this in the coming days, I will try to hack together my own "interim solution".

**Comment by cornedor** [comment]
I've added this in e6fb149088924193bf13cfc0babd40c818861d77 you can now update it. If you have issues with it don't hesitate to ask.
