### ISSUE TITLE
TypeError: Cannot read property 'Constants' of undefined  

### ISSUE THREAD

**Issue by lude1994** [cornedor/react-native-video-player#111]
I use react-native-video or react-native-video-player show  _TypeError: Cannot read property 'Constants' of undefined_  ,I dont know how to solve to it

**Comment by mayur-bhandari** [comment]
react-native link react-native-video-player

**Comment by TheRav3n** [comment]
Closing this issue as it can't be reproduced. Feel free to reopen and provide more details.
