### ISSUE TITLE
not displaying thumbnail in android

### ISSUE THREAD

**Issue by madhumatip** [cornedor/react-native-video-player#112]

**Comment by Gabsys** [comment]
Add props: 
thumbnail={{uri:YOUR_URL}}

**Comment by TheRav3n** [comment]
Closing as this thread is too old. If this is still happening, provide steps to reproduce or a full code example.

**Comment by Alex1899** [comment]
having the same issue on android

**Comment by MasterRedStorm** [comment]
I have as well.
using 
      thumbnail={{ uri: 'https://thumbs.dreamstime.com/z/example-red-tag-example-red-square-price-tag-117502755.jpg' }}
results in a black thumbnail

**Comment by Janviba911** [comment]
Same problem, can you please provide solution for the same ASAP?

> I have as well.
> using
> thumbnail={{ uri: 'https://thumbs.dreamstime.com/z/example-red-tag-example-red-square-price-tag-117502755.jpg' }}
> results in a black thumbnail

**Comment by rbbhure** [comment]
Same issue, still its in open state
