### ISSUE TITLE
Vertical video is stretched in Fullscreen mode

### ISSUE THREAD

**Issue by Gabsys** [cornedor/react-native-video-player#114]
When I play a vertical video, the video content is at the center with black gaps on the left & right which is normal & fine. However, once I go fullscreen, the video content will be stretched to fill up the whole screen instead of maintaining the black gaps on the left & right. Anyone manage to solve this issue?

**Comment by Gabsys** [comment]
Fixed by replacing the VideoView code in player_fullscreen.xml with

`<VideoView
            android:id="@+id/videoView"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:layout_centerInParent="true"
            android:layout_marginStart="0dp"
            android:layout_marginTop="0dp"
            android:layout_marginEnd="0dp"
            android:layout_marginBottom="0dp"
            android:onClick="onClick"
            android:padding="0dp" />`

**Comment by elifaahmet** [comment]
Hey @Gabsys can you please tell me where is this file?

**Comment by Gabsys** [comment]
> Hey @Gabsys can you please tell me where is this file?

android -> app -> src -> main -> res -> layout -> player_fullscreen.xml

**Comment by oguzhan10** [comment]
@Gabsys How did you manage to make it fullscreen?
