### ISSUE TITLE
Error on s3 video url

### ISSUE THREAD

**Issue by Taiyab123** [cornedor/react-native-video-player#119]
I am not able to play video from s3 URL. If anyone has solution regarding it, please response. Or we can play video from Vimeo only??

**Comment by TheRav3n** [comment]
[Amazon Tutorial](https://docs.sumerian.amazonaws.com/tutorials/create/beginner/s3-video/)

Make sure that both the bucket and video have public permission.

Add the following CORS configuration:
```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<CORSRule>
     <AllowedOrigin>*</AllowedOrigin>
     <AllowedMethod>GET</AllowedMethod>
     <MaxAgeSeconds>3000</MaxAgeSeconds>
</CORSRule>
</CORSConfiguration>
```
