### ISSUE TITLE
Broken with RN 0.62.0

### ISSUE THREAD

**Issue by slavikdenis** [cornedor/react-native-video-player#121]
![Screenshot_20200402-201015_IQ Metropolis](https://user-images.githubusercontent.com/15640932/78283481-23e68500-751e-11ea-87e3-2102394e73f7.jpg)

**Comment by drewpitchford** [comment]
Same issue here...Hopefully a fix is out soon? Or we just downgrade RN versions.

**Comment by guliash** [comment]
https://reactnative.dev/blog/2020/03/26/version-0.62#breaking-changes
'Remove PropTypes: We're removing propTypes from core components in order to reduce the app size impact of React Native core and to favor static type systems which check at compile time instead of runtime.'

**Comment by slavikdenis** [comment]
Temp fix is in `node_modules/react-native-video-player/index.js` delete/rename every `TouchableOpacity.propTypes`

**Comment by slavikdenis** [comment]
If anyone is interested, here is the component in typescript without proptypes. https://gist.github.com/slavikdenis/03e6d168cc45de24405a1b59edbedabe

**Comment by egarrett94** [comment]
[here](https://github.com/cornedor/react-native-video-player/pull/123) is a PR to update the types.

**Comment by TheRav3n** [comment]
This has been fixed with version 0.10.1 f4809d6c1ffab939ffb8cee70fb074cbb4fc9940

**Comment by slavikdenis** [comment]
@TheRav3n did not you mean https://github.com/cornedor/react-native-video-player/pull/123 ?

**Comment by TheRav3n** [comment]
@slavikdenis Haven't looked into PRs yet, but I fixed this myself with 0.10.1.
