### ISSUE TITLE
Looking for new maintainers

### ISSUE THREAD

**Issue by cornedor** [cornedor/react-native-video-player#122]
I'm looking for new maintainers, I no longer work with React Native projects and don't have a setup to develop this component any further.

If there is someone that would like to maintain this component I would be happy to transfer the ownership.

**Comment by NotMoni** [comment]
Hey, mate I can help. Feel free to contact me. 🦄

**Comment by bugsniper** [comment]
give me. What a good package!. I will maintain this.

**Comment by bugsniper** [comment]
@cornedor please give me ownership as well. ;)

**Comment by cornedor** [comment]
Hey, why do you need ownership at this moment? I would prefer to keep it for now until I know that it is in good hands, I hope you understand.

**Comment by fend25** [comment]
@cornedor thank you for the package and your work on it!

So, maybe give to @bugsniper merge permissions, because there are some simple but critical PRs (like #123)

**Comment by cornedor** [comment]
@bugsniper and @NotMoni are both collaborators, and as far as I know should have merge permissions. I'll update the npm packages asap when MR's are merged.

**Comment by TheRav3n** [comment]
Hello @cornedor, would like maintainer access. I would be happy to send a PR for the latest React Native issue.

**Comment by TheRav3n** [comment]
@cornedor If you can push 0.10.1 to npm, thank you!

**Comment by cornedor** [comment]
https://www.npmjs.com/package/react-native-video-player/v/0.10.1

**Comment by TheRav3n** [comment]
I'll be maintaining this package from now on so I'll close this issue. If anyone else wants to help, please reopen.

@cornedor I am not sure if you can get me access to upload to npm without losing ownership. If so, I'll ping you when we need to update.
