### ISSUE TITLE
RN 0.62 App crashes on Android right after building.

### ISSUE THREAD

**Issue by AdeelMughal** [cornedor/react-native-video-player#124]
When library is imported Android app crashes right after building. IOS working fine.

**Comment by SicraStudio** [comment]
Yes, getting:

`TypeError: undefined is not an object (evaluating '_reactNative.TouchableOpacity.propTypes.style`

As soon as I remove the `import VideoPlayer from 'react-native-video-player`, the app does not crash.

Any ideas?

**Comment by SicraStudio** [comment]
Workaround here: 

[https://github.com/cornedor/react-native-video-player/issues/121#issuecomment-608440166]

**Comment by TheRav3n** [comment]
This has been fixed with version 0.10.1 f4809d6c1ffab939ffb8cee70fb074cbb4fc9940
