### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by juddey** [cornedor/react-native-video-player#13]
This Just Works :tm: - Thank you. :heart:

**Comment by cornedor** [comment]
Thank you 😁

**Comment by thynan** [comment]
Well, if we have a thank-you Issue now, I might as well chip in: Thanks for the great library, and for the great support/responsiveness. Particularly for implementing the seekbar last month after I asked about it - works like a charm!

**Comment by TheRav3n** [comment]
Love to all, but this is not an issue. Closing ❤️
