### ISSUE TITLE
Black Screen on IOS React Native 66.4

### ISSUE THREAD

**Issue by zacdemi** [cornedor/react-native-video-player#144]
I created a clean react native project and followed the set up docs for react-native-video-player. The UI video window displays, but only shows a black background.![Simulator Screen Shot - iPhone 13 mini - 2022-01-12 at 10 39 31](https://user-images.githubusercontent.com/8942619/149201814-ce059a2b-714b-45fc-8e45-4e551fd6ff84.png)`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow strict-local
 */

import React from 'react';
import type {Node} from 'react';
import {
  SafeAreaView,
  StatusBar,
  StyleSheet,
  Text,
  useColorScheme,
  View,
} from 'react-native';

import {
  Colors,
} from 'react-native/Libraries/NewAppScreen';

import VideoPlayer from "react-native-video-player";

const App: () => Node = () => {
  const isDarkMode = useColorScheme() === 'dark';

  const backgroundStyle = {
    backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
  };

  return (
    <SafeAreaView style={backgroundStyle}>
        <StatusBar barStyle={isDarkMode ? 'light-content' : 'dark-content'} />
        <VideoPlayer
            video={{ uri: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4' }}
            videoWidth={1600}
            videoHeight={900}
            thumbnail={{ uri: 'https://i.picsum.photos/id/866/1600/900.jpg' }}
        />
    </SafeAreaView>
  );
};

const styles = StyleSheet.create({
  sectionContainer: {
    marginTop: 32,
    paddingHorizontal: 24,
  },
  sectionTitle: {
    fontSize: 24,
    fontWeight: '600',
  },
  sectionDescription: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '400',
  },
  highlight: {
    fontWeight: '700',
  },
});

export default App;
`

**Comment by zacdemi** [comment]
This only happens in the simulator. Works fine on a physical device.

**Comment by sreenumalae** [comment]
It happens in Physical devices also.
