### ISSUE TITLE
iOS seek bar not working: react-native 0.39.2

### ISSUE THREAD

**Issue by inv-jithin** [cornedor/react-native-video-player#15]
iOS seek bar not working in react-native version 0.39.2.

*Seekbar progress not working
*When touch on seekbar the video play from the start.

Mac OS
iPhone 6, 5s
OS iOS 10

This working smoothly on Android.

**Comment by PeTRoLi** [comment]
yes, I have this problem also

**Comment by cornedor** [comment]
@PeTRoLi do you also use 0.39.2?

**Comment by inv-jithin** [comment]
Actually, this is not react-native-video-player bug. This is react-native-video module issue. 
Please refer https://github.com/react-native-community/react-native-video/issues/428.

Solution also found on this link  https://github.com/react-native-community/react-native-video/issues/480

Please use this intermediate version : "react-native-video": "git://github.com/react-native-community/react-native-video.git#9bcf70cbb513402622bc114f93da751c28f15303", instead of something like 0.9.0.

**Comment by PeTRoLi** [comment]
@cornedor my versions;
react-native-video : 1.0.0
react-native-video-player : 0.6.1

**Comment by cornedor** [comment]
@inv-jithin Thanks for the info

@PeTRoLi could you try what @inv-jithin suggested?
