### ISSUE TITLE
video load really slow

### ISSUE THREAD

**Issue by fukemy** [cornedor/react-native-video-player#153]
tested with url:
http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

it's took~7 seconds to start render first frame, my network is good

**Comment by fukemy** [comment]
is this lib dead?

**Comment by fukemy** [comment]
@cornedor 
pls help

**Comment by cornedor** [comment]
react-native-video is used to play the video, can you check if your video plays fine with just react-native-video?

**Comment by fukemy** [comment]
thanks, im. trying to find problem in react-native-video
