### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_reactNative.NativeModules.UIManager.RCTVideo.Constants

### ISSUE THREAD

**Issue by azeezWebsultanate** [cornedor/react-native-video-player#155]
Error message : TypeError: undefined is not an object (evaluating '_reactNative.NativeModules.UIManager.RCTVideo.Constants

 "react-native": "0.67.4",
 "react-native-video-player": "^0.12.0",

<img width="442" alt="Screenshot 2022-05-31 at 7 11 30 PM" src="https://user-images.githubusercontent.com/87024456/171190016-2ab8038b-3356-4911-b458-7bd368db2c98.png">

I am facing the same issue in ios while I have to do pod install and icon install its keeps giving me the same issue

<img width="1440" alt="Screenshot 2022-05-31 at 7 23 53 PM" src="https://user-images.githubusercontent.com/87024456/171190546-7f94064e-1ee3-431b-a357-acc4c484e8a7.png">

And when I do pod install it doesn't add it in the pod file too.

**Comment by XiomaraG5** [comment]
did you solve?

**Comment by Amancoder006** [comment]
same error???

**Comment by TheDanielMoli** [comment]
Guys, this library has no maintainers anymore. Either become maintainers yourselves ( #157 ) or use another library.
