### ISSUE TITLE
Video Player Object is not stopped after switching to view

### ISSUE THREAD

**Issue by mosesmc52** [cornedor/react-native-video-player#16]
After I switch from the view that has the video player to another view. The video player doesn't stop or is not killed. I'm not sure that issue is a bug, but I would like to stop and remove the video player object.

**Comment by cornedor** [comment]
Do you switch the view using a router? Most routers keep the view loaded in the background thus the video will just continue.

When I have some time I'll look into how to do this, I don't think there is a nice way to do this currently.

**Comment by mosesmc52** [comment]
Thanks, 

I'll look into changing the view into a router. I'm not quite sure how to accomplish that. I'm using react-native-router-flux library to direct all of my routes.

**Comment by mosesmc52** [comment]
So I figured out my own issue. With the router library I'm using, it has this property called **ActionConst**. I just use the param called **ActionConst.RESET** found here:

https://github.com/aksonov/react-native-router-flux/blob/master/docs/API_CONFIGURATION.md#scene
