### ISSUE TITLE
TypeError: undefined is not an object (evaluating '_MaterialIcons.default.propTypes.style')

### ISSUE THREAD

**Issue by NLanese** [cornedor/react-native-video-player#162]
Whenever I add `import VideoPlayer from "react-native-video-player"` to any file, I get the following error whenever I try to even start the app...
```
TypeError: undefined is not an object (evaluating '_MaterialIcons.default.propTypes.style')


 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.


 ERROR  Invariant Violation: Module AppRegistry is not a registered callable module (calling runApplication). A frequent cause of the error is that the application entry file path is incorrect.
      This can also happen when the JS bundle is corrupt or there is an early initialization error when loading React Native.
```

I tried using `npm install material-icons` and `npm install material-icons --save` which worked for a little (?) and then I started getting the same error again, and rerunning that command did nothing. In its current state, this package seems to be project-breaking

**Comment by maoapp** [comment]
the same here :(

**Comment by marvelous-ikechi** [comment]
Same here

**Comment by roy-rayyone** [comment]
Try to upgrade your react-native-video to 5.2.1

**Comment by NLanese** [comment]
> Try to upgrade your react-native-video to 5.2.1

This appears to be the solution, I upgraded a while ago and fixed the issue. I suppose I just needed to wait for an update
