### ISSUE TITLE
video won't play until player.seek is called

### ISSUE THREAD

**Issue by Traviskn** [cornedor/react-native-video-player#18]
I'm using version 0.6.1 on Android, and am using a video from the filesystem.  I've noticed that after pressing the play button about a second or two passes and then the onLoad event fires, but the video won't play.  The controls show a pause button which indicates the video _should_ be playing.  Pressing pause and play again has no effect. However, if I drag the seekbar then the video will begin to play.  In order to work around the issue, I need to call `player.seek(0)` in the `onLoad` callback to get the video to start playing.

```
      <VideoPlayer
        ref={(video) => { this.video = video; }}
        video={{ uri: `file://${this.props.location}` }}
        videoWidth={width}
        videoHeight={height}
        customStyles={videoStyles}
        onLoad={() => {
          this.video.player.seek(0);
        }}
      />
```

I'm not sure if the issue is with this library or with react-native-video itself.

**Comment by cornedor** [comment]
Could you check what react-native-video version you're using?

**Comment by Traviskn** [comment]
I'm using version 1.0.0

**Comment by Traviskn** [comment]
I've been testing with other configurations, and I run into this issue even when setting the autoplay to true, so I'm thinking this is an issue with the underlying react-native-video library.  It could possibly be related to https://github.com/react-native-community/react-native-video/issues/494, where in some cases the paused prop is not working correctly.

**Comment by cornedor** [comment]
Do you have the same issue when you use `require('./someVideoFile.js')` in the source?

**Comment by Traviskn** [comment]
Sorry it's taken me so long to respond.  I've tested the video now using both the `require()` syntax , and from the file system with a 'file://' uri , and now I can't seem to reproduce the issue!  👻

**Comment by cornedor** [comment]
Good to hear it works again, if you ever have this issue again don't hesitate to comment here again.
