### ISSUE TITLE
Not able to reproduce videos without extension

### ISSUE THREAD

**Issue by cfontana0** [cornedor/react-native-video-player#19]
Hi! I'm not able to reproduce videos without extension downloaded from AWS S3.
They work correctly on Android, but do not work on iOS.
Can I indicate the content-type of something like that?

I was thinking to download the file, change the name, add the extension and reproduce it with the react-native-video-player. But it sounds complicated.

Any Idea?

I'm using:
    "react-native": "0.39.2",
    "react-native-video": "^0.9.0",
    "react-native-video-player": "^0.5.1",

Best,
Carlos

**Comment by cornedor** [comment]
I think this is an issue with react-native-video, could you check if this is the same issue you have: https://github.com/react-native-community/react-native-video/issues/398
