### ISSUE TITLE
Can not set videoWidth and videoHeight.

### ISSUE THREAD

**Issue by Symous** [cornedor/react-native-video-player#22]
Hi, I use this plugin in my Android app. this is my code:

```js
const {height, width} = Dimensions.get('window');
<VideoPlayer
   source={...}
   videoWidth={width}
   videoHeight={height}
/>
```

but the result is the video didn't fill my screen.

**Comment by cornedor** [comment]
The videoWidth and videoHeight is for the widht/height of the video itself to calculate the ratio, you can just use style for the width/height of the player. For example:
```
const {height, width} = Dimensions.get('window');
<VideoPlayer
   source={...}
   style={{ height, width }}
/>
```

**Comment by Symous** [comment]
Thank you @cornedor . :-)
