### ISSUE TITLE
Fullscreen mode : player turns black, no video plays, only audio.

### ISSUE THREAD

**Issue by dhawanheena26** [cornedor/react-native-video-player#23]
In full screen mode video does not show and on exiting the full screen mode, video does not play again. (ios)

**Comment by leogeng** [comment]
The same issue happen.

**Comment by cornedor** [comment]
What version of react-native-video and react-native are you using. And I assume this is on iOS?

**Comment by MarkMurphy** [comment]
Same issue here. react-native 45.1,  react-native-video 1.0.0, iOS

**Comment by cornedor** [comment]
Could you try playing the video using just [react-native-video](https://github.com/react-native-community/react-native-video) and calling `player.presentFullscreenPlayer()`

**Comment by mateofd** [comment]
Same here, RN 0.44.3 and react-native-video 1.0.0 and 2.0.0 (same behavior)

**Comment by cornedor** [comment]
I've had some stutters in Simulator too. Does someone have this issues on an actual device?

**Comment by dhawanheena26** [comment]
Yes, I got it on actual device as I was recording and testing from my phone, was not using on simulator

**Comment by cornedor** [comment]
What do you mean by recording?

**Comment by dhawanheena26** [comment]
Recording , means , I recorded a video using my phone, selected it and tried to play it in full screen. It even occurs when I select a video from camera.

**Comment by cornedor** [comment]
Can you share one of those video's? Also, what iPhone did you use?

**Comment by ParshantAroras** [comment]
Hi this problem is  in Simulator only . I have tested on iphone 5C and iphone 8+ working fine

**Comment by TheRav3n** [comment]
Closing as this is too old. If this is still happening, feel free to reopen and provide steps to reproduce or full code example.

**Comment by WesleyFaveri** [comment]
Anyone fixed this issue?
