### ISSUE TITLE
Android not working on device

### ISSUE THREAD

**Issue by mbelgrader** [cornedor/react-native-video-player#25]
It is working perfect on iOS and Android 7.0+ simulator.

But on the galaxy s8, it shows the thumbnail and controls. Then when pressing play, it is blank and does not play the video.

This is the device log:
`
05-24 16:31:50.313 13493-13493/? E/Zygote: v2
05-24 16:31:50.314 13493-13493/? E/Zygote: accessInfo : 0
05-24 16:33:47.939 13493-13770/com.thirsty E/OpenGLRenderer: resultIndex is -1, the polygon must be invalid!
05-24 16:33:47.978 13493-13770/com.thirsty E/OpenGLRenderer: resultIndex is -1, the polygon must be invalid!
05-24 16:33:48.617 13493-13770/com.thirsty E/OpenGLRenderer: resultIndex is -1, the polygon must be invalid!
05-24 16:33:57.028 13493-13493/com.thirsty E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
05-24 16:33:57.028 13493-13493/com.thirsty E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
05-24 16:33:57.928 13493-16121/com.thirsty E/MediaPlayer: error (1, -2147483648)
05-24 16:33:58.425 13493-13506/com.thirsty E/MediaPlayer: error (1, -2147483648)
`

Also doesn't work in Android 6.0 simulator.

**Comment by cornedor** [comment]
Are you able to play a video using just react-native-video?

**Comment by mbelgrader** [comment]
I tried using react-native-video and I get the same issue.

I found that it only happens when trying to play videos on the Android that were uploaded using an iOS. Which makes no sense to me. Any ideas why that is?

Also, it does play vids uploaded by android, but there is a really long wait to load and freezes the screen while loading.

**Comment by mbelgrader** [comment]
I found that changing this:

project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android')

to this:

project(':react-native-video').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-video/android-exoplayer')

in the settings.gradle file fixes everything.

**Comment by cornedor** [comment]
It propably wouldn't play iOS video's because it had a codec android doesn't support using the default player. But exoplayer seems to be a much better option, i've had more issues that didn't happen with exoplayer.
