### ISSUE TITLE
controlsTimeout not working well on Android

### ISSUE THREAD

**Issue by mbelgrader** [cornedor/react-native-video-player#30]
I have controlsTimeout set to 1000 since all my videos will be less than that. I just want to keep the controls visible the entire video.

It's working fine on iOS
On Android, if I set the timeout higher than the video length, the controls don't show up at all.

**Comment by cornedor** [comment]
1000 is not a typo? 1000 is one second and quite short. But i've added a disableControlsAutoHide prop  in v0.7.0 that you can use.

**Comment by mbelgrader** [comment]
Yes typo here, not in the code (10000). Awesome thanks!
