### ISSUE TITLE
this is a bug?

### ISSUE THREAD

**Issue by pheromone** [cornedor/react-native-video-player#33]
在 reatc-native 的该版本下安装,发生如下:
The installation under this version of reatc-native occurs as follows:

![539700c1-b7ca-4273-bf71-0fd02c5d9d8d](https://user-images.githubusercontent.com/14305431/27845578-169ea76e-6163-11e7-9a25-3aa6ca386740.png)

**Comment by Traviskn** [comment]
Have you installed `react-native-video` and `react-native-vector-icons`?  You will need to install both for this library to work.  The `react-native link react-native-video` command will not work until you have already installed `react-native-video`

Try the following commands:

`npm install --save react-native-video react-native-vector-icons`
`react-native link react-native-video`

**Comment by pheromone** [comment]
thank your help.

**Comment by cornedor** [comment]
I've clarified the readme a bit.
