### ISSUE TITLE
Feature request - bind events to player operations.

### ISSUE THREAD

**Issue by karan101292** [cornedor/react-native-video-player#34]
Hello, It would be great if we can bind callbacks on events such as `onStart`, `onEnd`, `onSeek`, `onPause`, `onResume` and it should have arg returning `currentTime` for the event.

Refer this JQuery player: https://github.com/Selz/plyr

**Comment by cornedor** [comment]
You can use the events from [react-native-community/react-native-video](https://github.com/react-native-community/react-native-video), there are also a few more events that are described in the README.md. I did add a few more today in 0.8.0.

**Comment by Sundin** [comment]
I couldn't get these callbacks to work, could you perhaps provide an example @cornedor?
