### ISSUE TITLE
Android 5.1 white screen

### ISSUE THREAD

**Issue by Odywan55** [cornedor/react-native-video-player#36]
Hello, have a white screen when press start , sound is playing , but no video,

before press start
<img width="406" alt="screen shot 2017-07-08 at 23 16 54" src="https://user-images.githubusercontent.com/13364000/27988780-aefe5130-6433-11e7-8192-0b164ee28915.png">
after 
<img width="453" alt="screen shot 2017-07-08 at 23 18 30" src="https://user-images.githubusercontent.com/13364000/27988783-ce3d2c24-6433-11e7-832b-2e8875ae321a.png">
on iOS is good

**Comment by cornedor** [comment]
can you try playing the video in another player on your phone?

**Comment by Odywan55** [comment]
this video is from vimeo service, 
i use it like here
 `import React, { Component } from 'react';
import { View, Text } from 'react-native';
import VideoPlayer from 'react-native-video-player';

const VIMEO_ID = '30968927';

export default class App extends Component {
  constructor() {
    super();

    this.state = {
      video: { width: undefined, height: undefined, duration: undefined },
      thumbnailUrl: undefined,
      videoUrl: undefined,
    };
  }

  componentDidMount() {
    global.fetch(`https://player.vimeo.com/video/${VIMEO_ID}/config`)
      .then(res => res.json())
      .then(res => this.setState({
        thumbnailUrl: res.video.thumbs['640'],
        videoUrl: res.request.files.hls.cdns[res.request.files.hls.default_cdn].url,
        video: res.video,
      }));
  }

  render() {
    return (
      <View style={{marginBottom : 8}}>
        <Text style={{ fontSize: 14, paddingVertical : 8 }}>{this.props.title.toUpperCase()}</Text>
        <VideoPlayer
          thumbnail={{ uri: this.state.thumbnailUrl }}
          video={{ uri: this.state.videoUrl }}
          videoWidth={this.state.video.width}
          videoHeight={this.state.video.height}
          duration={this.state.video.duration/* I'm using a hls stream here, react-native-video
            can't figure out the length, so I pass it here from the vimeo config */}
        />
      </View>
    );
  }
}
`

**Comment by HAPENLY** [comment]
@cornedor  I had the same problem, too. I tried to solve it and then failed
[ I had the same problem#45](https://github.com/cornedor/react-native-video-player/issues/45)

I have no problem with react-native-video

**Comment by Odywan55** [comment]
same story, on real device everything is good !
