### ISSUE TITLE
undefined is not an object RCTVideo.Constants

### ISSUE THREAD

**Issue by WillyRamirez** [cornedor/react-native-video-player#39]
error after installation on Windows -> Android 

undefined is not an object (evaluating '_reactNative.NativeModules.UIManager.RCTVideo.Constants')

Did anyone come across this issue before?

**Comment by WillyRamirez** [comment]
Had to add "compile project(':react-native-video')" in android/app/build.gradle

**Comment by RavindraMaddukuri** [comment]
Hi everyone,
      I am also facing this issue in react native ios same above
![Simulator Screen Shot - iPhone 6 Plus - 2019-06-10 at 09 57 48](https://user-images.githubusercontent.com/45200482/59172551-5033ae00-8b66-11e9-8fed-bf95bd77f4f0.png)

**Comment by WillyRamirez** [comment]
@RavindraMaddukuri sounds like a linking issue as well. Did you make sure it's linked correctly?
