### ISSUE TITLE
After video completed it showing nothing only black screen.

### ISSUE THREAD

**Issue by prashen** [cornedor/react-native-video-player#4]
I want that after watching video, it should back to it's thumbnail state. like this:
https://cloud.githubusercontent.com/assets/5449548/19279982/607c17f6-9001-11e6-9164-2242210e941c.png

but it's showing like this:
After completing video see screenshot:
https://cloud.githubusercontent.com/assets/5449548/19278867/a0899fa8-8ffc-11e6-9a3a-eb5c02d4ac5a.png

Please suggest how to fix this.

**Comment by cornedor** [comment]
I'm sorry for the late reply, I completely missed it. What the player currently does when the video is finished is to seek back to the start. I could implement an option to show the thumbnail instead.

**Comment by cornedor** [comment]
I've added a endWithThumbnail prop in 0.4.0.

**Comment by prashen** [comment]
It's working in my real device but on emulator it's not smooth. Its ok.. thanks @cornedor. I am also waiting for ur other todo list of this plugin.
