### ISSUE TITLE
Can't play .mp4 on android

### ISSUE THREAD

**Issue by WillyRamirez** [cornedor/react-native-video-player#41]
using an external uri, i cannot play mp4 videos on Android. On ios they work fine. On android when i use .webm they also work fine.

I have not here, not on react-native-video encountered anyone with this same issue. Can anyone please confirm that for example this test video works on android? 

http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4
```
 <VideoPlayer
            video={{ uri: 'http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_1mb.mp4'}}
            videoWidth={metrics.screenWidth}
            videoHeight={metrics.screenWidth * 1.2}
            loop={true}
            repeat
            autoplay
            hideControlsOnStart
            muted
            customStyles={{seekBar:{opacity: 0}, controls: {opacity: 0}}}
          />

```

**Comment by cornedor** [comment]
Did you try it with just react-native-video?

**Comment by WillyRamirez** [comment]
Hi @cornedor, no I haven't.
It mysteriously started working on my android device, still doesn't work on emulator though. Closing issue.
