### ISSUE TITLE
YellowBox.js:76 Using <Image> with children is deprecated and will be an error in the near future. Please reconsider the layout or use <ImageBackground>

### ISSUE THREAD

**Issue by AlmogRnD** [cornedor/react-native-video-player#42]
Is anyone else getting the following warning 

YellowBox.js:76 Using <Image> with children is deprecated and will be an error in the near future. Please reconsider the layout or use <ImageBackground> instead

**Comment by cornedor** [comment]
Hmm, this is will kick the react native version requirement up to 0.46.1. This probably wont be hard to fix, but I might publish it a bit later.

**Comment by AlmogRnD** [comment]
Great please let me know when it's done I will update my the package
