### ISSUE TITLE
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL initFileURLWithPath:]: nil string parameter'

### ISSUE THREAD

**Issue by AhSem** [cornedor/react-native-video-player#43]
I am using iOS device, and when I play the video, I got this error.

> Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSURL initFileURLWithPath:]: nil string parameter'

The video url is a rtsp live stream. The iOS device and the camera stream (rtsp) are in same local network.

What does this error imply?

**Comment by cornedor** [comment]
I'm not sure, but a it might be that your path is null instead of a string. Could you test it with react-native-video, if you've not done that already.

**Comment by AhSem** [comment]
Thank you for your reply. 
I would like to clarify on one thing beforehand. 
Can react-native-video-player and react-native-video play rtsp live stream from a network/ip camera?
This is not specified in the documentation, so I am not sure if this is an issue or it is just not supported at the moment.

**Comment by cornedor** [comment]
I’m not sure, you can test it by just importing react-native-video and copy the example from their GitHub
