### ISSUE TITLE
Android 6.0  Run successfully, show white screen, player control is not displayed

### ISSUE THREAD

**Issue by HAPENLY** [cornedor/react-native-video-player#45]
Run successfully, show white screen, player controls do not show.
IPhone, running without problems
![image](https://user-images.githubusercontent.com/9146468/29701261-459997a6-899d-11e7-9c95-4b436950d907.png)
![image](https://user-images.githubusercontent.com/9146468/29701341-b918210c-899d-11e7-94d5-1cd8dbdf7cac.png)

![image](https://user-images.githubusercontent.com/9146468/29701278-5e053f98-899d-11e7-9dae-67c1b0321a97.png)

**Comment by HAPENLY** [comment]
This is a bug. I have solved this problem. The problem is the problem of logic, when the thumbnail resources for the problem appears empty. The solution 1. author to modify the logic, 2. users add resources to the thumbnail.
![image](https://user-images.githubusercontent.com/9146468/29705831-4f675c68-89b2-11e7-8200-0e5f636a060c.png)
![image](https://user-images.githubusercontent.com/9146468/29705866-6aa43c08-89b2-11e7-84b2-b5593a70b01f.png)

**Comment by cornedor** [comment]
Thanks for digging into this and posting a comment here. Could you try to explain it a bit more, I don't really understand when this happens. Does this happen if the thumbnail URl is not valid?

**Comment by TheRav3n** [comment]
Closing as this is too old and author seems to have solved the issue.
