### ISSUE TITLE
Error while updating property 'backgroundColor' of a view managed by: RCTVideo

### ISSUE THREAD

**Issue by krishbhattacharyya** [cornedor/react-native-video-player#46]
**Environment:**
react-native: 0.44.0
node 7.9.0
"react-native-video-player": "^0.8.1",

**Target Platform:**
Android Emulator ( Nougat )

**Development Operating System:**
Ubuntu

**Steps to Reproduce:**
1) react-native run-android
2) Click on the play icon in the video player.

**Expected Behavior**
Video should play on the click.

**Extra info**
Android Emulator ( MarsheMallow ) - Working properly 

![screenshot_1503915842](https://user-images.githubusercontent.com/10433734/29769815-91d7dbfa-8c09-11e7-9992-eee462bf85a9.png)

**Comment by krishbhattacharyya** [comment]
I think the problem is due to - "react-native-video": "^1.0.0" ( dependency of this package )

In the latest version of  "react-native-video" it seems work in Android Emulator ( Nougat ).

I have made basic player with the help of "react-native-video": "^2.0.0"- 
It is working fine for me :)

Sharing screens shots- 

I think if "react-native-video" will be updated & also needed some change in your code. It will solved. 

Thanks for this beautiful package.

![screenshot_1504086388](https://user-images.githubusercontent.com/10433734/29866740-f593c3be-8d96-11e7-8175-af53569a860f.png)
![screenshot_1504086401](https://user-images.githubusercontent.com/10433734/29866741-f5bf897c-8d96-11e7-971b-78ec75cf5b1c.png)

**Comment by cornedor** [comment]
react-native-video is now updated. Is it fixed for you now?

**Comment by krishbhattacharyya** [comment]
Thanks @cornedor I will check .. & inform u soon.

**Comment by krishbhattacharyya** [comment]
Thanks @cornedor ... Now this is working properly. I have checked. You can close this issue.

**Comment by cornedor** [comment]
Thanks for the update, I'll close it now.
