### ISSUE TITLE
Is there a way to use onLoad property from react-native-video?

### ISSUE THREAD

**Issue by vasilycrespo** [cornedor/react-native-video-player#47]
Hello, considering that the plugin uses react-native-video, is there a way to use the property onLoad to retrieve the video information on load? eg:

`{"canStepForward":true,"canStepBackward":true,"canPlayReverse":true,"canPlaySlowForward":true,"canPlayFastForward":true,"naturalSize":{"orientation":"portrait","height":1920,"width":1080},"canPlaySlowReverse":true,"currentTime":0,"duration":2.14}`

I need to get the natural video size and orientation. Or does this plugin provide a different method to achieve this? thanks.

**Comment by mateofd** [comment]
Just pass an onLoad prop to the VideoPlayer:

```javascript
<VideoPlayer
  endWithThumbnail
  video={{ uri: this.props.videoURL }}
  resizeMode={'contain'}
  onLoad={(event) => {
      console.log('VideoPlayer onLoad, ', event);
   }}/>
```

Something like that. I looked at the source code and figured this out.

Regards!

**Comment by cornedor** [comment]
The onLoad event is indeed triggered by react-native-video's onLoad event. See: https://github.com/cornedor/react-native-video-player/blob/master/index.js#L187
