### ISSUE TITLE
video not adjusting to player size

### ISSUE THREAD

**Issue by tarun29061990** [cornedor/react-native-video-player#5]
This is my VideoPlayer code:-

```
<VideoPlayer
          thumbnail={{uri: this.props.data.videoUrl.split('//')[1] }}
          video={{uri: this.props.data.videoUrl.split('//')[1] }}
          duration={10}
          videoWidth={Dimensions.get('window').width}
          videoHeight={200}
          style={styles.backgroundVideo}
        />
```
![a658241f-0a3c-4f1a-b61b-f72c3fb9cb4a](https://cloud.githubusercontent.com/assets/1535607/19629379/bc1613f2-9991-11e6-96c3-036d1e6366d5.jpeg)

Please help?

**Comment by cornedor** [comment]
You might want to use `resizeMode="cover"`. If not, could you give an example of what you want?

**Comment by tarun29061990** [comment]
Thanks you

**Comment by tarun29061990** [comment]
Some parts of the video is getting clipped when using resizeMode="cover". Please help

**Comment by cornedor** [comment]
Can you give an example of the result you want?

**Comment by tarun29061990** [comment]
This is the video I am recording:
![whatsapp image 2016-11-02 at 10 24 59 am](https://cloud.githubusercontent.com/assets/1535607/19917187/f63ee750-a0e6-11e6-921d-a764efe24981.jpeg)

And when I play it:
![whatsapp image 2016-11-02 at 10 25 00 am](https://cloud.githubusercontent.com/assets/1535607/19917200/0b2df0c0-a0e7-11e6-9e81-0e7061819506.jpeg)

So the video is getting clipped. Below is my code for the video player:
```
<VideoPlayer
          thumbnail={{uri: this.props.data.videoUrl.split('//')[1] }}
          video={{uri: this.props.data.videoUrl.split('//')[1] }}
          duration={this.props.data.duration}
          style={styles.backgroundVideo}
          resizeMode={"cover"}
        />
```

**Comment by cornedor** [comment]
Are you sure that it is not in the video file? The camera preview in Android sometimes has a different resolution than the output file. I've had issues with this myself.

**Comment by tarun29061990** [comment]
I have played this video file in VLC and its perfect. There is no problem with the video file. The flow is I am recording a video, storing it locally and then playing it in the next view. I think there is some problem with the dimensions of the video. Can you suggest something?

**Comment by cornedor** [comment]
Could you share that video so I can test with it?
