### ISSUE TITLE
Video Play in Android version 7.0/24

### ISSUE THREAD

**Issue by MSSPL-PiyaleeMaiti** [cornedor/react-native-video-player#53]
In android version 7.0 and api version 24, when we play a video then it will showing below error. 
![screenshot_1506002940](https://user-images.githubusercontent.com/20696057/30700294-d026d100-9f04-11e7-92ea-61911cbdb3b9.png)

I found a solution that we should overlride the video-player mode_module package video background color. Now I want to know that when we trying to override the video style like below:
```
customStyles={{
    video : {},
 }}
```

but its cannot override the style, still getting above error. How could i solve.

In node_module their is condition for 25 but no condition for 24. Below from node_module/react-native-video-player package::
```
  video: Platform.Version === 25 ? {} : {
    backgroundColor: 'black',
  },
```

**Comment by cornedor** [comment]
24 and above hasn't a background set with the v0.8.3

**Comment by MSSPL-PiyaleeMaiti** [comment]
Solved

**Comment by jiyeon-dino** [comment]
how to solved?
