### ISSUE TITLE
Android 4.4

### ISSUE THREAD

**Issue by Odywan55** [cornedor/react-native-video-player#59]
hello, android 4.4 (x86 with google api's)  not working, no sound and no video : 
<img width="427" alt="screen shot 2017-09-28 at 21 35 58" src="https://user-images.githubusercontent.com/13364000/30984189-4d8f37fa-a495-11e7-9546-29208355618a.png">

**Comment by cornedor** [comment]
Could you try playing a video using react-native-video

**Comment by Odywan55** [comment]
Sorry, on real device everything is good !
