### ISSUE TITLE
Hard to show control bar

### ISSUE THREAD

**Issue by callmejm** [cornedor/react-native-video-player#60]
First thanks to this awesome plugin, you done a great job. But I facing a problem that quite hard to show the control bar when tapping the video player. I have to tap very quick in few time only show the control bar. Is there any option can make it easily to tap only one time in video player to display the control bar ?

**Comment by JayricMok** [comment]
it fixed when using https://github.com/ShariqMush/react-native-fullscreenvideo-player . But can you add the total duration and current play time inside this plugin. It will help a lot. Thanks

**Comment by cornedor** [comment]
Is it a problem in fullscreen?

**Comment by JayricMok** [comment]
@cornedor not in fullscreen in normal view, quite hard to show control bar. And also hope can support android in fullscreen mode, [fullscreen player](https://github.com/ShariqMush/react-native-fullscreenvideo-player) this can use for fullscreen, however it will buffer again each time when trigger fullscreen, not a good user experience. The original player you manage, it have auto detect the video ratio to add the black bar between also.

**Comment by cornedor** [comment]
Ah ok, I haven't had issues with the control bar not showing up, what device are you using?

**Comment by JayricMok** [comment]
@cornedor i use this [fullscreen player](https://github.com/ShariqMush/react-native-fullscreenvideo-player) index.js the control bar problem fixed. I using huawei p9 plus

**Comment by arielalvarez88** [comment]
This happens to me. I tried to wrap the renderVideo in a TouchableOpacity and call showControls in the onPress , but it doesn't work. For some reason it only works when I touch with 2 fingers.

**Comment by kriziacamilleuayan** [comment]
this is also happening to me, i have to tap fast to show the controls.

`"react-native": "0.56.0"`
`"react-native-video-player": "0.9.0"`
`"react-native-video": "3.2.0"`

**Comment by TheRav3n** [comment]
Closing as this issue is too old. Feel free to reopen if you are still facing it and provide more info.
