### ISSUE TITLE
seek on start

### ISSUE THREAD

**Issue by JayricMok** [cornedor/react-native-video-player#66]
I would like to make a direct seek when click `onStartPress()`. 

    onStartPress(){
      if(this.props.video.uri != ''){
        this.setState({
          isPlaying: true,
          isStarted: true,
        });
        console.log("THIS ON START");
        this.hideControls();
        this.player.seek(parseFloat("3.0"));
      }
    }

But I'm getting this error

 `Cannot read property 'seek' of undefined`

**Comment by bgoyal2222** [comment]
+1

**Comment by cornedor** [comment]
The player should have a ref, see the updated example where stop/pause/resume is called in the player.

https://github.com/cornedor/react-native-video-player/commit/e02b327a17f87921af9d81f07d098cc98462d858#diff-6f5ffa383d424bfb3992760d1100f603
