### ISSUE TITLE
RN 0.39 Do not seek to start after playing

### ISSUE THREAD

**Issue by shaftwin** [cornedor/react-native-video-player#7]
Hi,

I m on RN 0.39, after playing video or audio, the player do not seek to 0 and i cannot replay.
Someone know how can we do it ?
Cordialy !!

**Comment by cornedor** [comment]
I fixed this issue for Android, there is however still a bug if you're using iOS10 in react-native-video (https://github.com/react-native-community/react-native-video/issues/335)
