### ISSUE TITLE
Animated component breaks the app

### ISSUE THREAD

**Issue by IvRRimum** [cornedor/react-native-video-player#72]
Using react native starterkit, installed this library. i get this:

<img width="370" alt="screen shot 2017-12-06 at 11 47 14" src="https://user-images.githubusercontent.com/5957079/33655222-27dd9206-da7b-11e7-8ad0-b23c36dcebb0.png">

Note that audio of the video is still playing in the background(even with this error on).

I debugged and found out that once i remove Animated component from rendering, it doesn't show the error anymore.

here is how i use it:
`        {<VideoPlayer
              source={{ uri: 'http://download.streammonkey.com/khQvpN5/transcoded/somevideo/0.mp4' }}
              style={styles.video}
              onBack={() => {console.log("yeahh")}}
          />}`

Any ideas?

**Comment by cornedor** [comment]
Is the video in a Animated component? I don't really understand how it is related.

**Comment by TheRav3n** [comment]
Closing as this issue is too old. If this is still happening, feel free to reopen. Provide steps to reproduce or full code example.
