### ISSUE TITLE
base64 video thrown an exception

### ISSUE THREAD

**Issue by ergunyasar** [cornedor/react-native-video-player#73]
Hello,

I am trying to play video with base64 data uri, however I am getting a NSInvalidArgumentException error. [NSURL initFileURLWithPath:]: nil string parameter'

Is there any support or workaround for this?

**Comment by ErnestGrey** [comment]
Have you tried `video={require('../path/to/yourVideo.mp4')}`

**Comment by cornedor** [comment]
See https://github.com/react-native-community/react-native-video/issues/266
