### ISSUE TITLE
 Android Full Screen Mode Video Playing from Starting

### ISSUE THREAD

**Issue by dip77** [cornedor/react-native-video-player#77]
In Android Full Screen Mode ,Video playing from Starting rather than continuing from where I pressed Full Screen
For the Android Full Screen I Have used,
NativeModules.BridgeModule.showFullscreen(uri);

RN 0.43

Would really Appreciate if someone can solve this issue, had spent too much time solving this and
Product need to release ASAP.

**Comment by dip77** [comment]
i solved this issue by writing native code,
**VideoPlayer (in file index.js)**
onToggleFullScreen() {
    if(Platform.OS === "android")
    {
      var uri = this.props.video.uri;
      **NativeModules.BridgeModule.showFullscreen(uri,currentTime*1000)**;//passing MS as duration
      //currentTime is stored in state and changes whenever onProgress gets called
 }
    else
    {
      this.player.presentFullscreenPlayer();
    }

**BrdigeModule.java**

 @ReactMethod
    public void showFullscreen(String videoUri,int duraitonToSeek) {
        duration=duraitonToSeek; // duration is static variable
        Context context = getReactApplicationContext();
        Intent intent = new Intent(context, VideoActivity.class); 
        intent.putExtra("VIDEO_URL",videoUri);
        getCurrentActivity().startActivity(intent);
    }

**VideActivity.java**

myVideoView.setOnPreparedListener(new MediaPlayer.OnPreparedListener() {
                public void onPrepared(MediaPlayer mp) {
                    progressDialog.dismiss();
                    **myVideoView.seekTo(BridgeModule.duration);**
                    myVideoView.start();
                }
            });

**Comment by kunal-oxl** [comment]
@dip77 

where to find the BridgeModule.java and VideActivity.java files?

**Comment by kunal-oxl** [comment]
let me know if there's any better library for this too :/
