### ISSUE TITLE
Cannot read property 'seek' of null

### ISSUE THREAD

**Issue by nickrobinson352** [cornedor/react-native-video-player#79]
I get the following error everytime the video reaches the end. 'Cannot read property 'seek' of null'

` <VideoPlayer
                            thumbnail={require('../../img/Media.png')}
                            endWithThumbnail
                            video={{ uri: videoobj }}
                        />`

**Comment by cornedor** [comment]
Did you install react-native-video?

**Comment by nickrobinson352** [comment]
Yes. This is what I have in my package.json. The video works well except get that exception as soon as the OnEnd is fired.

` "react-native-video": "^2.0.0",
  "react-native-video-player": "^0.9.0",`

**Comment by cornedor** [comment]
Could you try `react-native-video-player@0.9.0`

**Comment by gvillenave** [comment]
Same error in 0.9.1, everything works fine in 0.9.0. I believe this is caused by f6de282c95f9b2725efd7f1d699a0201240345d2

**Comment by nickrobinson352** [comment]
react-native-video-player@0.9.0 worked !

**Comment by qasimalbaqali** [comment]
Still facing this issue even if downgrading to 0.9.0

**Comment by a-eid** [comment]
I'm also getting a slightly different error after downgrading to 0.9.0

![video-thumbnail](https://user-images.githubusercontent.com/19273413/42162962-b3b3fcba-7dce-11e8-9cb8-9ddbd3a6cc77.jpg)

**Comment by a-eid** [comment]
@qasimalbaqali I've restarted it a couple of times, still having the same issue.

**Comment by cornedor** [comment]
This should now be fixed in the latest version
