### ISSUE TITLE
fullscreen button on Android does not show

### ISSUE THREAD

**Issue by SujaYuga** [cornedor/react-native-video-player#87]
I tried instructions as mentioned in PR#38. No errors but the fullscreen button on Android does not show. I am using react native video player version #0.9.1. React Native Version 0.53.0. Any update please?

**Comment by ODINA101** [comment]
same here :/

**Comment by sherazi-maavan** [comment]
fuck you !

**Comment by ODINA101** [comment]
fuck your girlfriend,mother,father,sister,brother,neighbors,aunt,uncle !!!

2018-05-24 13:31 GMT+04:00 Shahzaib Ali Sherazi <notifications@github.com>:

**Comment by TheRav3n** [comment]
Closing as duplicate of #52
