### ISSUE TITLE
Cleanly disable controls

### ISSUE THREAD

**Issue by carlbolduc** [cornedor/react-native-video-player#88]
Is there a way to completely disable the controls and progression bar? I would like to drive the video programmatically with custom buttons.

**Comment by TheRav3n** [comment]
Closing as this makes no sense. If you don't need the controls, just switch to `react-native-video`. The whole point of this package is the controls.

**Comment by gignupg** [comment]
I disagree! Correct me if I'm wrong but as far as I know `react-native-video` doesn't allow you to programmatically play/pause the video which makes building custom controls difficult.
