### ISSUE TITLE
Video orientation change in Andriod O

### ISSUE THREAD

**Issue by NitishAgrawal** [cornedor/react-native-video-player#94]
The video is working well in iOS also in Android less then O But in API level 26 Android O it's orientation fix to landscape.

**Comment by petrogad** [comment]
@NitishAgrawal - I believe this should fix your problem. 

https://github.com/cornedor/react-native-video-player/issues/101#issuecomment-424831921

Cheers

**Comment by TheRav3n** [comment]
Closing as duplicate of #101
