### ISSUE TITLE
this url can not paly

### ISSUE THREAD

**Issue by pheromone** [cornedor/react-native-video-player#95]
http://wxsnsdy.tc.qq.com/105/20210/snsdyvideodownload?filekey=30280201010421301f0201690402534804102ca905ce620b1241b726bc41dcff44e00204012882540400&bizid=1023&hy=SH&fileparam=302c020101042530230204136ffd93020457e3c4ff02024ef202031e8d7f02030f42400204045a320a0201000400
this url can not paly.why?

**Comment by TheRav3n** [comment]
Closing as I have no idea which is the format of that video and this thread is too old. Feel free to reopen providing more info.
