### ISSUE TITLE
Audio is not playing on iOS

### ISSUE THREAD

**Issue by j3rin** [cornedor/react-native-video-player#96]
Video plays, but no audio. Any solutions?

Thank you in advance

**Comment by ravi8x** [comment]
I got the same problem. it turns out to be my phone is in silent mode :D I hope it's not the same case with you

**Comment by AyushAppin** [comment]
Any Solution?

**Comment by TheRav3n** [comment]
Audio is working on iOS as of now. If you are still having this issue, please provide steps to reproduce or a full code example.
